<?php
/*------------------------------------------------------------------------
 # VT RevolutionSlider - Version 1.0
 * Copyright (C) 2013 The VT Theme. All Rights Reserved.
 * @license - GNU/GPL, http://www.gnu.org/licenses/gpl.html
 * Author: VT Theme
 * Websites: http://www.vtthemepro.com
-------------------------------------------------------------------------*/
global $var_vttheme; 
$config = $this->getConfigObject();
$uq = rand().time();
$l = $var_vttheme->getParam('layout_home');
?>

	<div class="box" style="width:100%;height:400px;margin:0px auto;position:relative;">	
		<div class="pic" style="width:100%;height:400px;overflow:hidden;">
			<ul>
				<li style="list-style-type:none;width:100%;height:400px;position:relative;overflow:hidden;background:url('http://bdbbuy.com/media/wysiwyg/images/slide/bg-s1-01.png') center">

				</li>
				<a href="{{store url='shippingarea'}}"><li style="list-style-type:none;width:100%;height:400px;position:relative;overflow:hidden;background:url('http://bdbbuy.com/media/wysiwyg/images/slide/bg-s2-01.png') center"></a>

				</li>
				<li style="list-style-type:none;width:100%;height:400px;position:relative;overflow:hidden;background:url('http://bdbbuy.com/media/wysiwyg/images/slide/bg-s3-01.png') center">

				</li>
				<li style="list-style-type:none;width:100%;height:400px;position:relative;overflow:hidden;background:url('http://bdbbuy.com/media/wysiwyg/images/slide/bg-s4-01.png') center">

				</li>
				<li style="list-style-type:none;width:100%;height:400px;position:relative;overflow:hidden;background:url('http://bdbbuy.com/media/wysiwyg/images/slide/bg-s5-01.png') center">

				</li>
			</ul>
		</div>
		<div class="navv" style="width:100px;height:14px;position:absolute;bottom:10px;left:50%;margin-left:-50px">
			<ul>
				<li class="bg" style="list-style-type:none;width:12px;height:12px;float:left;margin-right:5px;cursor:pointer;
			border:1px solid #fff;"></li>
				<li style="list-style-type:none;width:12px;height:12px;float:left;margin-right:5px;cursor:pointer;
			border:1px solid #fff;"></li>
				<li style="list-style-type:none;width:12px;height:12px;float:left;margin-right:5px;cursor:pointer;
			border:1px solid #fff;"></li>
				<li style="list-style-type:none;width:12px;height:12px;float:left;margin-right:5px;cursor:pointer;
			border:1px solid #fff;"></li>
				<li style="list-style-type:none;width:12px;height:12px;float:left;margin-right:5px;cursor:pointer;
			border:1px solid #fff;"></li>
			</ul>
		</div>
	</div>

	<script type="text/javascript">
	var i = -1;
	var time=0;
	window.onload=function(){ 
		junmper();
		time=setInterval("junmper()",3700);
		$(".navv ul li").click(function(){
			i=$(this).index();
			$(".navv ul li").eq(i).addClass("bg").siblings().removeClass("bg");
			$(".pic ul li").eq(i).fadeIn(100).siblings().fadeOut(100);
			$(".pic ul li").eq(i).find(".img1").css({left:"-760px"});
			$(".pic ul li").eq(i).find(".img2").css({display:"none",left:"-15px"});
			$(".pic ul li").eq(i).find(".img1").animate({left:"0px"},500,function(){
				$(".pic ul li").eq(i).find(".img2").css("display","block");
				$(".pic ul li").eq(i).find(".img2").animate({left:"0px"},500);
			});

		})
		$(".navv ul li").hover(function(){
			clearInterval(time);
		},function(){
			time=setInterval("junmper()",3700);
		})
	} 
	function junmper(){
		i++;
		if(i>4)
			i=0;
		$(".navv ul li").eq(i).addClass("bg").siblings().removeClass("bg");
		$(".pic ul li").eq(i).fadeIn(100).siblings().fadeOut(100);
		$(".pic ul li").eq(i).find(".img1").css({left:"-760px"});
		$(".pic ul li").eq(i).find(".img2").css({display:"none",left:"-15px"});
		$(".pic ul li").eq(i).find(".img1").animate({left:"0px"},500,function(){
			$(".pic ul li").eq(i).find(".img2").css("display","block");
			$(".pic ul li").eq(i).find(".img2").animate({left:"0px"},500);
		});

	}

	</script>