<?php
 /**
 * Onestepcheckout Extension
 *
 *
 * PHP versions 4 and 5
 *
 * LICENSE: This source file is subject to version 3.0 of the PHP license
 * that is available through the world-wide-web at the following URI:
 * http://www.store.vt.com/license.txt.  If you did not receive a copy of
 * the PHP License and are unable to obtain it through the web, please
 * send a note to admin@vt.com so we can mail you a copy immediately.
 *
 * @category   Magento Extensions
 * @package    Vt_Onestepcheckout
 * @author     Vt <sales@vt.com>
 * @copyright  2007-2011 Vt
 * @license    http://www.store.vt.com/license.txt
 * @version    1.0.1
 * @link       http://www.store.vt.com
 */
 ?>
<?php if (!($_shippingRateGroups = $this->getShippingRates())): ?>
    <p><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></p>
<?php else: ?>
<dl class="sp-methods">
    <?php $shippingMe = array(); ?>
    <?php $_sole = count($_shippingRateGroups) == 1; foreach ($_shippingRateGroups as $code => $_rates): ?>
        <dt><?php echo $this->getCarrierName($code) ?></dt>
        <dd>
            <ul>
            <?php $_sole = $_sole && count($_rates) == 1; foreach ($_rates as $_rate): ?>
                <?php $shippingMe[] = "'".$_rate->getCode()."':".(float)$_rate->getPrice(); ?>
                <li>
                   <?php if ($_rate->getErrorMessage()): ?>
                    <ul class="messages"><li class="error-msg"><ul><li><?php echo $_rate->getErrorMessage() ?></li></ul></li></ul>
                   <?php else: ?>
                        <?php if ($_sole) : ?>
                        <span class="display"><input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>" checked="checked" /></span>
                        <?php else: ?>
                        <input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' checked="checked"' ?> class="radio" onchange="return includingShipping('<?php echo $_rate->getCode();?>');"/>

                        <script type="text/javascript">
                        //<![CDATA[
                            <?php if ($_rate->getCode()===$this->getAddressShippingMethod()): ?>
                                lastPrice = <?php echo (float)$_rate->getPrice(); ?>;
                            <?php endif; ?>
                        //]]>
                        </script>

                        <?php endif; ?>
                        <label for="s_method_<?php echo $_rate->getCode() ?>"><?php echo $_rate->getMethodTitle() ?>
                        <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                        <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                        <?php echo $_excl; ?>
                        <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                            (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                        <?php endif; ?>
                        </label>
                   <?php endif ?>
                </li>
            <?php endforeach; ?>
            </ul>
        </dd>
		<?php if($code == 'localpickup') : ?>
		<dd>
			<div id="store-location-content" style="<?php if($this->getAddressShippingMethod() !='localpickup_localpickup') :?>display:none <?php endif;?>">
				<?php echo $this->getChildHtml('localpickup') ?>
			</div>
		</dd>
		<?php endif ?>
    <?php endforeach; ?>
</dl>
<script type="text/javascript">
//<![CDATA[
    <?php if (!empty($shippingMe)): ?>
        var shippingMe = {<?php echo implode(',',$shippingMe); ?>};
    <?php endif; ?>

	<?php if (Mage::getStoreConfig("carriers/localpickup/active", Mage::app()->getStore()->getId())):?>
		var billingLocalPickup = new Localpickup('<?php echo Mage::helper('localpickup')->getUpdateStoreUrl(); ?>');
		document.observe('dom:loaded', function() {
			if($('s_method_localpickup_localpickup')){
				if($('s_method_localpickup_localpickup').checked){
					$('store-location-content').show();
					billingLocalPickup.selectStoreShipping(true);
				}
			}
		});
		$$('input[type="radio"][name="shipping_method"]').each(function(el){
			Event.observe(el, 'click', function(){
				if (el.checked == true) {
					var getShippingCode = el.getValue();
					if(getShippingCode == 'localpickup_localpickup'){
						$('store-location-content').show();
						billingLocalPickup.selectStoreShipping(true);
					} else {
						billingLocalPickup.selectStoreShipping(false);
					}
					return false;
				}
		   });
		});
	<?php endif;?>
    function includingShipping(getShippingCode)
    {
        <?php if (!empty($shippingMe)): ?>
            var newPrice = shippingMe[getShippingCode];
            if (!lastPrice) {
                lastPrice = newPrice;
                quoteBaseGrandTotal += newPrice;
            }
            if (newPrice != lastPrice) {
                quoteBaseGrandTotal += (newPrice-lastPrice);
                lastPrice = newPrice;

            }
        <?php endif; ?>
        checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
        return false;
    }
//]]>
</script>
<?php endif; ?>
