<?php
 /**
 * Onestepcheckout Extension
 *
 *
 * PHP versions 4 and 5
 *
 * LICENSE: This source file is subject to version 3.0 of the PHP license
 * that is available through the world-wide-web at the following URI:
 * http://www.store.vt.com/license.txt.  If you did not receive a copy of
 * the PHP License and are unable to obtain it through the web, please
 * send a note to admin@vt.com so we can mail you a copy immediately.
 *
 * @category   Magento Extensions
 * @package    Vt_Onestepcheckout
 * @author     Vt <sales@vt.com>
 * @copyright  2007-2011 Vt
 * @license    http://www.store.vt.com/license.txt
 * @version    1.0.1
 * @link       http://www.store.vt.com
 */
?>
<?php 
$shippingmethod = $this->getAddressShippingMethod() ? $this->getAddressShippingMethod() : Mage::getStoreConfig('onestepcheckout/general/default_shipping_method') ;
$_shippingRateGroups = $this->getShippingRates();
?>

 <?php if (!($_shippingRateGroups)): ?>
    <strong><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></strong>
<?php else: ?>
<dl class="shipment-methods">
        <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
                    <dd><?php echo $this->getCarrierName($code) ?></dd>
                <?php foreach ($_rates as $_rate): ?>
                    <dt style="margin-bottom: 5px;">

                       <?php if ($_rate->getErrorMessage()): ?>
                        <ul class="messages"><li class="error-msg"><ul><li><?php echo $_rate->getErrorMessage() ?></li></ul></li></ul>
                       <?php else: ?>
                            <input name="shipping_method" type="radio" class="validate-one-required-by-name" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$shippingmethod) echo ' checked="checked"' ?>')" />
                            <label for="s_method_<?php echo $_rate->getCode() ?>"><!--<b><?php echo $this->getCarrierName($code) ?>:</b>--> <?php echo $_rate->getMethodTitle() ?>
                            <strong>
                            <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                            <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>

                            <?php echo $_excl; ?>
                            <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                            <?php endif; ?>
                            </strong>
                            </label>
                       <?php endif ?>
                    </dt>
                <?php endforeach; ?>
				<?php if($code == 'localpickup') : ?>
				<dd>
					<div id="store-location-content" style="<?php if($this->getAddressShippingMethod() !='localpickup_localpickup') :?>display:none <?php endif;?>">
						<?php echo $this->getLayout()->createBlock('localpickup/checkout_store')->toHtml() ?>
					</div>
				</dd>
				<?php endif ?>
        <?php endforeach; ?>
    </dl>

<?php endif; ?> 

    <script type="text/javascript" >
	<?php if (Mage::getStoreConfig("carriers/localpickup/active", Mage::app()->getStore()->getId())):?>
		var billingLocalPickup = new Localpickup('<?php echo Mage::helper('localpickup')->getUpdateStoreUrl(); ?>');
		document.observe('dom:loaded', function() {
			if($('s_method_localpickup_localpickup')){
				if($('s_method_localpickup_localpickup').checked){
					$('store-location-content').show();
					billingLocalPickup.selectStoreShipping(true);
				}
			}
		});
		$$('input[type="radio"][name="shipping_method"]').each(function(el){
			Event.observe(el, 'click', function(){
				if (el.checked == true) {
					var getShippingCode = el.getValue();
					if(getShippingCode == 'localpickup_localpickup'){
						$('store-location-content').show();
						billingLocalPickup.selectStoreShipping(true);
					} else {
						billingLocalPickup.selectStoreShipping(false);
					}
					return false;
				}
		   });
		});
	<?php endif;?>
	   $$('dl.shipment-methods input').invoke('observe', 'click', function() {
			shipping.loadReview();
			var payment_methods = $('ajax-payment-methods');
			payment_methods.update('<div class="loading-ajax">&nbsp;</div>');
			payment.loadPayment();
		});
   
	</script>

  <div id="onepage-checkout-shipping-method-additional-load">
       <?php if (!$this->getQuote()->isVirtual()): ?>

    <?php echo $this->helper('giftmessage/message')->getInline('onepage_checkout', $this->getQuote(), $this->getDontDisplayContainer()) ?>
<?php endif; ?>
    </div>
